version: 1.2.1

endpoints:
  bedrock:
    enabled: true
    titleModel: "anthropic.claude-sonnet-4-20250514-v1:0"
    defaultModel: "anthropic.claude-sonnet-4-20250514-v1:0"
    streamRate: 35
    models:
      default:
        # Claude 4 Models
        - "anthropic.claude-sonnet-4-20250514-v1:0"     # Claude Sonnet 4 (Default)
        - "anthropic.claude-opus-4-1-20250805-v1:0"     # Claude Opus 4.1 (Most Advanced)
        - "anthropic.claude-opus-4-20250514-v1:0"       # Claude Opus 4
        # Claude 3.x Models
        - "anthropic.claude-3-7-sonnet-20250219-v1:0"   # Claude 3.7 Sonnet
        - "anthropic.claude-3-5-sonnet-20241022-v2:0"   # Claude 3.5 Sonnet v2
        - "anthropic.claude-3-5-sonnet-20240620-v1:0"   # Claude 3.5 Sonnet
        - "anthropic.claude-3-5-haiku-20241022-v1:0"    # Claude 3.5 Haiku
        - "anthropic.claude-3-opus-20240229-v1:0"       # Claude 3 Opus
        - "anthropic.claude-3-sonnet-20240229-v1:0"     # Claude 3 Sonnet
        - "anthropic.claude-3-haiku-20240307-v1:0"      # Claude 3 Haiku
        - "anthropic.claude-instant-v1"                 # Claude Instant
        # Meta Llama Models
        - "meta.llama3-1-70b-instruct-v1:0"             # Llama 3.1 70B
        - "meta.llama3-1-8b-instruct-v1:0"              # Llama 3.1 8B
        - "meta.llama3-70b-instruct-v1:0"               # Llama 3 70B
        - "meta.llama3-8b-instruct-v1:0"                # Llama 3 8B
        # Mistral Models
        - "mistral.mistral-large-2407-v1:0"             # Mistral Large
        - "mistral.mistral-large-2402-v1:0"             # Mistral Large (Previous)
        - "mistral.mixtral-8x7b-instruct-v0:1"          # Mixtral 8x7B
        - "mistral.mistral-7b-instruct-v0:2"            # Mistral 7B
        # Amazon Titan Models
        - "amazon.titan-text-premier-v1:0"              # Titan Premier
        - "amazon.titan-text-express-v1"                # Titan Express
        - "amazon.titan-text-lite-v1"                   # Titan Lite
        # Cohere Models
        - "cohere.command-r-plus-v1:0"                  # Command R+
        - "cohere.command-r-v1:0"                        # Command R
        # AI21 Models
        - "ai21.j2-ultra-v1"                            # Jurassic-2 Ultra
        - "ai21.j2-mid-v1"                              # Jurassic-2 Mid

fileConfig:
  endpoints:
    default:
      fileLimit: 100
      fileSizeLimit: 200  # MB per file
      totalSizeLimit: 1000  # MB total
      supportedMimeTypes:
        # Documents
        - "application/pdf"
        - "text/plain"
        - "text/csv"
        - "text/html"
        - "text/markdown"
        - "application/rtf"
        # Microsoft Office
        - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        - "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        - "application/msword"
        - "application/vnd.ms-excel"
        - "application/vnd.ms-powerpoint"
        # Images (for multimodal models)
        - "image/jpeg"
        - "image/png"
        - "image/gif"
        - "image/webp"
        # Code files
        - "application/json"
        - "application/xml"
        - "text/javascript"
        - "text/css"

# Tools Configuration
tools:
  - google_search:
      enabled: true
  - bing_search:
      enabled: true
  - web_browser:
      enabled: true
  - calculator:
      enabled: true
  - code_interpreter:
      enabled: false  # Enable if Python runtime available

# RAG Configuration
ragConfig:
  enabled: true
  api:
    url: "http://rag-api:8000"
  embedding:
    provider: "bedrock"
    model: "amazon.titan-embed-text-v2:0"
  chunking:
    strategy: "semantic"
    size: 1500
    overlap: 200
  retrieval:
    topK: 5
    similarityThreshold: 0.7
    rerankingEnabled: true

registration:
  enabled: true
  allowedDomains:
    - "company.com"
  socialLogins:
    - "google"
    - "github"

# Interface Configuration
interface:
  messageLimit: 40  # Messages per conversation before warning
  maxContextTokens: 8192
  showModelTokenCounts: true
  endpointsMenu: true
